### ISSUE TITLE
Serverlog spamm paper1.15

### ISSUE THREAD

**Issue by Desoru** [IHasName/CustomHeads#17]
I am currently with my server on papermc1.15
The Server gets spammed, can try updating it?
[latest.log](https://github.com/IHasName/CustomHeads/files/4006218/latest.log)

**Comment by IHasName** [comment]
Hi there,
The Spam is caused by an Method thats outdated in 1.15, which is currently not supported by the Plugin.
I'm currently working on the 1.15 Update but it might take some time since it's the End of the Year.
If you want to get notified when the Update comes out be sure to join my [Discord](https://discord.gg/wc5AzEm)

Happy New New Year =]
